#  patternedglass mods.toml
modLoader="javafml"
loaderVersion="[43,)"
license="LGPL-3.0"
issueTrackerURL="https://github.com/thenamesnano/Patterned-Glass/issues"

[[mods]]
modId="patternedglass"
version="${file.jarVersion}"
displayName="Patterned Glass"
updateJSONURL="https://gist.githubusercontent.com/thenamesnano/a78c86f9a56a60dcfb9aff7a51061963/raw"
displayURL="https://www.curseforge.com/minecraft/mc-mods/patterned-glass"
logoFile= "patternedglass.png"
credits="Thanks to noxzos_ for the idea on Minecraft Forum and the ReviversMC Team for maintaining the Fabric version."
authors="Nano (thenamesnano)"
description='''
A mod that adds in patterned glass.
'''

[[dependencies.patternedglass]]
    modId="forge"
    mandatory=true
    versionRange="[43,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.patternedglass]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,1.20)"
    ordering="NONE"
    side="BOTH"
